import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');

test('runtime migrations complete direct operational storage',async()=>{const m5=await read('supabase/migrations/005_enterprise_runtime_completion.sql');const m6=await read('supabase/migrations/006_runtime_replay_and_integrity.sql');const m7=await read('supabase/migrations/007_procurement_projection_and_permissions.sql');for(const table of ['finance_events','hr_requests','employee_daily_reports','operation_status_history','document_registry'])assert.match(m5,new RegExp(`create table if not exists public\.${table}`));for(const table of ['inventory_movements','purchase_requests','collection_events','quality_cases','operational_tasks','driver_events'])assert.match(m5,new RegExp(`alter table public\.${table} add column if not exists source_audit_id`));assert.match(m5,/project_enterprise_structured_audit/);assert.match(m5,/daily_attendance_summary/);assert.match(m5,/driver_daily_summary/);assert.match(m6,/audit_enterprise_structured_replay_trigger/);assert.match(m6,/flag_negative_inventory/);assert.match(m6,/queue_approval_notification/);assert.match(m6,/queue_missing_daily_reports/);assert.match(m7,/project_supplier_quote_request/);assert.match(m7,/source_event_type/);assert.match(m7,/supplier_quote_request_projection_trigger/);});

test('operations API supports management actions and pending approvals',async()=>{const management=await read('api/_lib/routes/management.js');for(const marker of ["action==='set_status'","action==='create_task'","action==='approval_decision'","action==='enqueue_notification'",'approvals_pending','notifyOperationSource'])assert.match(management,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(management,/enterprise_operation_status/);assert.match(management,/next_document_no/);});

test('operations action UI is injected without adding a function',async()=>{const index=await read('index.html');const ui=await read('assets/cloud-operations-actions.js');assert.match(index,/cloud-operations-actions\.js/);for(const marker of ['bhOpsNewTask','create_task','set_status','approval_decision','bhOperationNotify'])assert.match(ui,new RegExp(marker));});

test('reports center covers every operational department',async()=>{const index=await read('index.html');const ui=await read('assets/cloud-reports.js');const management=await read('api/_lib/routes/management.js');assert.match(index,/cloud-reports\.js/);assert.match(management,/export async function reports/);assert.match(management,/daily_attendance_summary/);assert.match(management,/driver_daily_summary/);for(const section of ['sales','maintenance','inventory','collections','finance','purchases','quality','attendance','fleet','tasks','dailyReports'])assert.match(ui,new RegExp(section));assert.match(ui,/exportCsv/);assert.match(ui,/printReport/);});

test('documents are registered and publicly verifiable by code',async()=>{const documents=await read('api/_lib/bot-documents.js');const verify=await read('verify-document.html');const management=await read('api/_lib/routes/management.js');assert.match(documents,/document_registry/);assert.match(documents,/createHash\('sha256'\)/);assert.match(documents,/verify-document\.html\?code=/);assert.match(management,/export async function documentVerification/);assert.match(verify,/\/api\/documents\/verify\?code=/);assert.doesNotMatch(documents,/quickchart\.io/);});

test('notification schedulers are disabled and Telegram remains on-demand only',async()=>{const notifications=await read('api/_lib/bot-notifications.js');const cron=await read('api/cron/manager-brief.js');const operational=await read('.github/workflows/operational-schedule.yml');const telegram=await read('.github/workflows/bot-schedules.yml');for(const marker of ['processNotificationOutbox','retryFailedNotifications','queueDailyReportReminders','notification_outbox'])assert.match(notifications,new RegExp(marker));assert.match(cron,/CRON_SECRET غير مضبوط/);assert.match(cron,/onDemandOnly:true/);assert.match(cron,/enabled:false/);assert.doesNotMatch(cron,/mode==='all'/);for(const workflow of [operational,telegram]){assert.match(workflow,/workflow_dispatch/);assert.doesNotMatch(workflow,/\bschedule:/);assert.doesNotMatch(workflow,/\bcron:/);assert.doesNotMatch(workflow,/curl --fail/);assert.doesNotMatch(workflow,/BINHAMID_CRON_URL|BOT_CRON_URL/);}});

test('runtime readiness requires the complete schema 024 financial command center and employee identity contract',async()=>{const runtime=await read('api/_lib/routes/system-runtime.js');const router=await read('api/router.js');for(const table of ['finance_events','hr_requests','employee_daily_reports','operation_status_history','document_registry','daily_report_batches','daily_report_sales_lines','daily_report_cash_movements','cost_ledger','sales_payment_allocations','fifo_rebuild_runs','financial_periods','credit_override_requests','unified_assets','compliance_documents','restore_test_runs','handover_acceptance_runs','chart_of_accounts','journal_entries','journal_entry_lines','telegram_update_receipts','user_invitations'])assert.match(runtime,new RegExp(table));for(const marker of ['LATEST_REQUIRED_VERSION=24',"purchase_requests:['source_event_type','source_event_id']",'migration_history.sequence','directOperationsSchema:24','dailyReportCustomerMaster:true','governanceCenter:true','accountingLedger:true','correctReversalLedger:true','telegramUpdateIdempotency:true','factoryOperationalReset:true','employeeNickname:true','financialDirector:true','administrativeControlCenter:true'])assert.ok(runtime.includes(marker),`missing ${marker}`);assert.match(router,/systemRuntime\.databaseReadiness/);assert.match(router,/systemRuntime\.status/);assert.match(router,/accounting\.accounting/);});

test('public routes stay centralized without a duplicate daily report importer',async()=>{const config=JSON.parse(await read('vercel.json'));const rewrites=new Map(config.rewrites.map(x=>[x.source,x.destination]));const removedDailyRoute=String.fromCharCode(47)+'api/imports/daily-report';assert.equal(rewrites.get('/api/reports'),'/api/router?route=reports');assert.equal(rewrites.get('/api/documents/verify'),'/api/router?route=documents/verify');assert.equal(rewrites.get('/api/accounting'),'/api/router?route=accounting');assert.equal(rewrites.has(removedDailyRoute),false);const router=await read('api/router.js');assert.match(router,/'reports':management\.reports/);assert.match(router,/'documents\/verify':management\.documentVerification/);assert.match(router,/'accounting':accounting\.accounting/);assert.doesNotMatch(router,/imports\/daily-report/);});

test('the original daily summary and movement screens share one parser extension',async()=>{const index=await read('index.html');const parser=await read('assets/daily-summary-parser.js');const fix=await read('assets/existing-daily-import-fix.js');const cloud=await read('assets/cloud-control.js');assert.match(index,/daily-summary-parser\.js/);assert.match(index,/existing-daily-import-fix\.js/);assert.doesNotMatch(index,/daily-report-import\.js/);for(const marker of ['parseDirectSales','parseTreasuryCollections','treasuryCode'])assert.match(parser,new RegExp(marker));for(const marker of ['opsImportDailySummary','opsImportDailyMovement','sourceFileFingerprint','saveMovementCollections'])assert.match(fix,new RegExp(marker));for(const marker of ['bhReadCookie','bhAutoApply','bhCloudApplyImport'])assert.match(cloud,new RegExp(marker));});

test('activation documents cover schema seven and external activation steps',async()=>{const guide=await read('docs/PHASE_TWO_ACTIVATION.md');const v7=await read('docs/RUNTIME_SCHEMA_7.md');for(let n=1;n<=6;n++)assert.match(guide,new RegExp(`00${n}_`));for(const marker of ['BINHAMID_CRON_SECRET','BINHAMID_CRON_URL','PUBLIC_APP_URL','webhook-v3','ready=true'])assert.match(guide,new RegExp(marker));for(const marker of ['007_procurement_projection_and_permissions.sql','schemaVersion=7','directOperationsSchema=7','purchase_requests'])assert.match(v7,new RegExp(marker));});

test('every approved employee can submit a suggestion or problem that is persisted and sent to management',async()=>{
  const [{roleHomeRows,SIMPLE_DEFS},forms,bot,handler]=await Promise.all([
    import('../api/_lib/bot-enterprise-defs.js'),
    read('api/_lib/bot-enterprise-forms.js'),
    read('api/_lib/bot-enterprise.js'),
    read('api/_lib/telegram-webhook-handler.js')
  ]);
  const roles=['admin','manager','accountant','mechanic','block_sales','concrete_sales','collector','driver','employee','warehouse','fuel_operator','hr','procurement','quality'];
  for(const role of roles){
    const callbacks=roleHomeRows(role).flat().map(button=>button.callback_data);
    assert.ok(callbacks.includes('ent:management_suggestion'),`missing suggestion for ${role}`);
    assert.ok(callbacks.includes('ent:management_problem'),`missing problem for ${role}`);
  }
  assert.equal(SIMPLE_DEFS.management_suggestion.prefix,'SUG');
  assert.equal(SIMPLE_DEFS.management_problem.prefix,'PRB');
  assert.match(bot,/startEnterpriseForm\(message,identity,'management_suggestion'\)/);
  assert.match(bot,/startEnterpriseForm\(message,identity,'management_problem'\)/);
  assert.match(forms,/enterprise_operation_created/);
  assert.match(forms,/active=eq\.true&role=in\.\(admin,manager\)/);
  assert.match(forms,/management_feedback_received/);
  assert.match(forms,/notification\.delivered/);
  assert.match(handler,/result\.text\?handleText\(message,group,identity,result\.text/);
});
