import crypto from 'node:crypto';
import { body,errorResponse,json,method } from '../http.js';
import { assertSameOrigin,issueDeviceSession } from '../device-session.js';
import { insert,patch,select } from '../supabase.js';
import { sendMessage } from '../telegram.js';
import { config } from '../config.js';
const clean=(v,n=160)=>String(v??'').trim().slice(0,n),validDevice=v=>/^dev-[A-Za-z0-9-]{8,150}$/.test(String(v||'')),validId=v=>/^\d{5,20}$/.test(String(v||'')),hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex'),same=(a,b)=>{const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length===y.length&&x.length>0&&crypto.timingSafeEqual(x,y);};
async function user(id){const r=(await select('user_channels',`channel=eq.telegram&external_id=eq.${encodeURIComponent(id)}&active=eq.true&select=user_id,app_users(id,full_name,role,active)&limit=1`).catch(()=>[]))?.[0]?.app_users;return r?.active?r:null;}
async function row(device){return(await select('device_enrollments',`device_id=eq.${encodeURIComponent(device)}&select=device_id,metadata&limit=1`).catch(()=>[]))?.[0]||null;}
async function save(device,values){const old=await row(device);if(old)return patch('device_enrollments',`device_id=eq.${encodeURIComponent(device)}`,values);return insert('device_enrollments',[{device_id:device,status:'pending',requested_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString(),metadata:values.metadata||{}}]);}
export async function requestWebLogin(req,res){if(!method(req,res,['POST']))return;try{assertSameOrigin(req);const input=await body(req,4096),device=clean(input.deviceId),telegram=clean(config.telegramOwnerId,20);if(!validDevice(device)||!validId(telegram))throw Object.assign(new Error('حساب مالك Telegram غير مضبوط في الخادم.'),{status:503});const active=await user(telegram);if(!active)throw Object.assign(new Error('حساب المالك لم يُعتمد في Telegram بعد.'),{status:403});const old=await row(device),prev=old?.metadata?.web_login||{},now=Date.now();if(Number(prev.sentAt||0)>now-45000)throw Object.assign(new Error('تم إرسال رمز قبل قليل. انتظر 45 ثانية.'),{status:429});const code=String(crypto.randomInt(100000,1000000)),login={telegram,codeHash:hash(device+':'+code),sentAt:now,expiresAt:now+300000,attempts:0};await save(device,{status:'pending',updated_at:new Date().toISOString(),metadata:{...(old?.metadata||{}),web_login:login}});await sendMessage(telegram,`<b>رمز دخول موقع مصنع بن حامد</b>\n\nالرمز: <code>${code}</code>\nصالح لمدة 5 دقائق. لا تشاركه.`);json(res,200,{ok:true});}catch(e){errorResponse(res,e);}}
export async function verifyWebLogin(req,res){if(!method(req,res,['POST']))return;try{assertSameOrigin(req);const input=await body(req,4096),device=clean(input.deviceId),telegram=clean(config.telegramOwnerId,20),code=clean(input.code,12);if(!validDevice(device)||!validId(telegram)||!/^\d{6}$/.test(code))throw Object.assign(new Error('بيانات الدخول غير صحيحة.'),{status:400});const old=await row(device),login=old?.metadata?.web_login||{};if(String(login.telegram)!==telegram||Number(login.expiresAt||0)<Date.now()||Number(login.attempts||0)>=5||!same(login.codeHash,hash(device+':'+code))){await save(device,{metadata:{...(old?.metadata||{}),web_login:{...login,attempts:Number(login.attempts||0)+1}}});throw Object.assign(new Error('الرمز غير صحيح أو منتهي.'),{status:401});}const active=await user(telegram);if(!active)throw Object.assign(new Error('الحساب غير معتمد.'),{status:403});await save(device,{status:'approved',app_user_id:active.id,updated_at:new Date().toISOString(),metadata:{...(old?.metadata||{}),web_login:{verifiedAt:Date.now(),telegram}}});const session=issueDeviceSession(req,res,device,active.id);json(res,200,{ok:true,user:{id:active.id,name:active.full_name||'',role:active.role||'employee'},expiresAt:new Date(session.exp*1000).toISOString()});}catch(e){errorResponse(res,e);}}
