import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const file=resolve('legacy.html'),source=readFileSync(file,'utf8'),lines=source.split(/\r?\n/),styleBlocks=[...source.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)].map(match=>match[1]),scriptBlocks=[...source.matchAll(/<script\b(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].map(match=>match[1]);
const css=styleBlocks.join('\n'),javascript=scriptBlocks.join('\n'),functions=[...javascript.matchAll(/(?:function\s+([A-Za-z_$][\w$]*)\s*\(|(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>)/g)].map(match=>match[1]||match[2]).filter(Boolean),functionCounts=new Map();
for(const name of functions)functionCounts.set(name,(functionCounts.get(name)||0)+1);
const duplicates=[...functionCounts].filter(([,count])=>count>1).map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count),globals=[...javascript.matchAll(/(?:^|\n)\s*(?:var|let|const)\s+([A-Za-z_$][\w$]*)/g)].map(match=>match[1]),listeners=(javascript.match(/addEventListener\s*\(/g)||[]).length,inlineHandlers=(source.match(/\son(?:click|change|input|submit|load|keydown|keyup)=/gi)||[]).length,printMarkers=(source.match(/@media\s+print|window\.print\s*\(|print\s*\(/gi)||[]).length;
const longFunctions=[];for(const match of javascript.matchAll(/function\s+([A-Za-z_$][\w$]*)\s*\([^)]*\)\s*\{/g)){const start=match.index||0;let depth=0,end=start;for(let index=javascript.indexOf('{',start);index<javascript.length;index++){if(javascript[index]==='{')depth++;else if(javascript[index]==='}'){depth--;if(depth===0){end=index;break;}}}const length=javascript.slice(start,end+1).split(/\r?\n/).length;if(length>=50)longFunctions.push({name:match[1],lines:length});}
const report={generatedAt:new Date().toISOString(),file:'legacy.html',bytes:Buffer.byteLength(source),lines:lines.length,css:{blocks:styleBlocks.length,lines:css?css.split(/\r?\n/).length:0},javascript:{blocks:scriptBlocks.length,lines:javascript?javascript.split(/\r?\n/).length:0,functionCount:functions.length,globalDeclarationCount:globals.length,eventListeners:listeners,inlineHandlers,printMarkers,longFunctions:longFunctions.sort((a,b)=>b.lines-a.lines).slice(0,50),duplicateFunctionNames:duplicates.slice(0,50)},externalDailyImporter:source.includes('daily-summary-parser.js')||source.includes('existing-daily-import-fix.js')};
const output=resolve(process.argv[2]||'legacy-analysis.json');writeFileSync(output,JSON.stringify(report,null,2));console.log(JSON.stringify(report));
